### ISSUE TITLE
Tracking window vanished from existence

### ISSUE THREAD

**Issue by Gabbalo** [MidoriKami/CurrencyAlert#26]
Ever since I installed my new monitor (5120x1440) the window vanished and I am unable to have it back on my screen.
Things I have done to solve it: Disable/Enable the plugin, Un-/Reinstall it, activate a red border / red background for it to be more visible, set the position to 0/0 (anchor everywhere) ... but the result is just nothing.
The chat alert (something I actually don't have enabled normally because it's just not visible enough to me) IS working, so the plugin seems to be loaded properly. 
Any ideas?

**Comment by MidoriKami** [comment]
The tracking "window" is not a window, it's a UI element that is injected into the game layer.

Right click the plugin in the plugin installer and click "Reset Data and Reload" or something along those lines. There's a good chance your configuration file is corrupted.

**Comment by MidoriKami** [comment]
Marking as stale. Likely user side corruption.

**Comment by nonamethanks** [comment]
@MidoriKami actually this happened to me as well after the latest update. 

I didn't change any setting, but the window is not visible anymore. 
These are the settings after data reset. The tracking window is still nowhere to be found.
![Image](https://github.com/user-attachments/assets/fbdf6461-7402-4028-9328-e918a1ef0214)

**Comment by MidoriKami** [comment]
send config file

**Comment by nonamethanks** [comment]
Here it is.

[CurrencyAlert.config.json](https://github.com/user-attachments/files/18924197/CurrencyAlert.config.json)

**Comment by Gabbalo** [comment]
For me, the issue was solved as explained by resetting the config. 
For new setup it helped, to crate a well signaling background to the window - like in red

**Comment by nonamethanks** [comment]
Ah, I see, the problem was that by resetting the settings, all the currencies lost the "overlay" option, so basically by default the overlay shows nothing. Weird design but ok. 

Still not sure why it stopped working after the update, but after resetting and rechecking overlay on all the currencies now it works again.

**Comment by MidoriKami** [comment]
There was an issue with the update that is causing peoples configurations to get completely reset, a hotfix for this issue was just released.
